name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Install and cache requirements"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.4.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install && poetry build
  unit-test:
    name: "Run unit tests with coverage"
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.4.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run coverage run
      - run: poetry run coverage report
  static-analysis:
    name: "Static analysis with ruff"
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.4.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run ruff check .
  security-analysis:
    name: "Security analysis with bandit"
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.4.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run bandit -c pyproject.toml -r .
  formatting:
    name: "Check formatting with black"
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.4.0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run black --check .
